parameters:
  - name: awsAccessKeyId
    displayName: AWS access key id
    type: string
    default: $(TF_BACKEND_AWS_KEY_ID)
  - name: awsSecretKeyId
    displayName: AWS secret key id
    type: string
    default: $(TF_BACKEND_AWS_SECRET_KEY)
  - name: awsDefaultRegion
    displayName: AWS default region
    type: string
    default: $(TF_BACKEND_AWS_REGION)

steps:
  - task: PowerShell@2
    displayName: Terraform Set Credentials
    name: tfSetCredentials
    timeoutInMinutes: 360
    inputs:
      targetType: inline
      script: |
        $Env:AWS_ACCESS_KEY_ID="${{ parameters.awsAccessKeyId }}"
        $Env:AWS_SECRET_ACCESS_KEY="${{ parameters.awsSecretKeyId }}"
        $Env:AWS_DEFAULT_REGION="${{ parameters.awsDefaultRegion }}"
      errorActionPreference: stop
      showWarnings: true
      pwsh: true
