name: 1.0$(Rev:.r)

pool:
  vmImage: ubuntu-latest

trigger:
  batch: true
  branches:
    include:
      - "main"

pr:
  branches:
    include:
      - '*'

variables:
  - name: WORKSPACE_PREFIX
    value: terraform-backend-

stages:
  - stage: production
    displayName: Production
    variables:
      - template: templates/variables/production.ap-southeast-2.yml
      - group: production.ap-southeast-2
      - group: infracost
    jobs:
      - template: templates/tasks/plan-and-approve.yml
        parameters:
          terraformVariablesFile: variables/$(ENVIRONMENT).$(AWS_DEFAULT_REGION).tfvars
          terraformWorkspace: $(WORKSPACE_PREFIX)$(ENVIRONMENT)
          environment: $(ENVIRONMENT)
