environment="Production"
region="us-east-1"
bucket_name="expensely-terraform-production-us-east-1"
dynamodb_name="expensely-terraform-lock-production-us-east-1"
username="terraform-us-east-1"
iam_path="terraform/us-east-1"
iam_policy_prefix="terraform-us-east-1"
key_name="terraform"